baseURL = "https://pgersl.xyz/"
title = "Petr Geršl"
languageCode = "en-us"
defaultContentLanguage = "en"
uglyURLs = "false"
enableEmoji = "true"
[params]
    description = "Personal website of Petr Geršl"
[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = "1"
    [[menu.main]]
        identifier = "notes"
        name = "Notes"
        url = "/notes"
        weight = "2"
    [[menu.main]]
        identifier = "articles"
        name = "Articles"
        url = "/articles"
        weight = "3"
[frontmatter]
    date = ['date', 'publishDate', 'lastmod']
    expiryDate = ['expiryDate']
    lastmod = [':git', 'lastmod', 'date', 'publishDate']
    publishDate = ['publishDate', 'date']
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = "true"
    [markup.tableOfContents]
        ordered = true
        startLevel = 0
        endLevel = 3